token = "token"

max_reviews_size = 25
min_scanned = 500
min_votes = 3
queue_length = 1000
flag_threshold = 0.5

bot_server = 784984468251082752
scan_channels = [
  289482554250100736
]
flag_channel = 784984545131888711
review_channel = 785310590498504754
sanitize_channel = 785310898805407755

reviewer_category = 793586695282884609
review_role = 786276045355221055

admin_users = [
  248245568004947969,
  240973228632178689,
  123879073972748290,
  69198249432449024,
  125233822760566784
]

reaction_emojis = [
  '<:insult:788917079972511774>',
  '<:severe_toxic:788916179048595496>',
  '<:identity_hate:788916178734546955>',
  '<:threat:788916178784354345>',
  '<:nsfw:788916179301433355>',
  'ðŸ“¥',
  'ðŸ§¹',
  '<:greentick:567088336166977536>',
  '<:redtick:567088349484023818>'
]

blacklist = []

[database]
# The keyword arguments that get passed into database connectors.
# If you're using the docker-compose, you do not need to change this.
host = "db"
port = 5432
user = "postgres"
password = "password"
database = ""
max_size = 20
timeout = 60