token = "token"

bot_server = 784984468251082752

scan_channels = [
  289482554250100736
]

flag_channel = 784984545131888711
review_channel = 785310590498504754
sanitize_channel = 785310898805407755

admin_users = [
  248245568004947969,
  240973228632178689,
  123879073972748290,
  69198249432449024,
  125233822760566784
]

reaction_emojis = [
  'ğŸŸ§',
  'ğŸŸ©',
  'ğŸŸ¨',
  'ğŸŸ¥',
  'ğŸ—³ï¸',
  'ğŸ§¹',
  '<:greentick:567088336166977536>',
  '<:redtick:567088349484023818>'
]

blacklist = []